title: "Insight Nusantara"
description: "Insight Nusantara - Berita, informasi, dan update terkini dari seluruh dunia"
url: "https://premierbolagg.github.io"  # URL utama situs
baseurl: "/Insight-Nusantara"  # Jika situs Anda berada di subfolder GitHub Pages

# Pastikan timezone dan markdown sesuai
timezone: Asia/Jakarta  
markdown: kramdown  

# Plugin tambahan jika diperlukan
plugins:
  - jekyll-sitemap  # Otomatis buat sitemap.xml untuk SEO
  - jekyll-seo-tag  # Tambahkan meta tag SEO (opsional)

# Pastikan rssfeed.xml tidak dihapus oleh Jekyll
include:
  - rssfeed.xml

# Exclude file yang tidak perlu untuk mempercepat build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
