name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Jalankan saat ada push ke branch utama
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Website (Static HTML)
        run: |
          mkdir -p public
          cp -r * public/  # Copy semua file ke folder public, kecuali .git dan .github

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
