name: Build and Deploy Jekyll Site

on:
  deployment_status:
    types: [success]  # Trigger hanya jika deployment sukses

permissions:
  contents: read
  statuses: write  # Memberikan izin untuk update status commit

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    if: success()  # Hanya berjalan jika build sukses
    permissions:
      statuses: write  # Memberikan izin update status commit
    steps:
      - name: Report Build Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const sha = context.payload.deployment_status?.sha || context.sha;
            const run_id = context.runId;

            github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: "success",
              target_url: `https://github.com/${owner}/${repo}/actions/runs/${run_id}`,
              description: "Build completed successfully!",
              context: "Build Status"
            });

  deploy:
    runs-on: ubuntu-latest
    needs: report-build-status
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Tambahan checkout agar deployment memiliki akses ke kode sumber

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
