name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2  # ✅ Gunakan v2 yang stabil
        with:
          path: _site

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Report Build Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const run_id = context.run_id;
            github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: "success",
              target_url: `https://github.com/${owner}/${repo}/actions/runs/${run_id}`,
              description: "Build completed successfully!",
              context: "Build Status"
            });

  deploy:
    runs-on: ubuntu-latest
    needs: report-build-status
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # ✅ Gunakan versi terbaru yang tersedia
